name: build-tests
on:
  - push
jobs:
  tests:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Run Unit test(s)
        run: |
          pytest -s test_unit_*.py
